# Generated by Django 4.1.2 on 2022-10-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coverpic',
            field=models.ImageField(default='defaultcoverpic.jpg', upload_to='coverpic'),
        ),
    ]
