# Generated by Django 4.1.2 on 2022-10-20 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_coverpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='follower_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
                ('viewing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
