# Generated by Django 4.1.2 on 2022-10-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower_count',
            name='profile_user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='follower_count',
            name='viewing_user',
            field=models.CharField(max_length=200),
        ),
    ]
